[package]
name = "taxi-soberano-barcelona"
version = "1.0.0"
authors = ["Vicente <SembrandoEsperanzaUtil>"]
edition = "2021"
description = "Infraestructura de soberanía digital para el taxi autónomo de Barcelona. Basado en el honor y la protección mutua."

[dependencies]
# Aquí es donde en el futuro conectaremos la seguridad biométrica real
